/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-clipboard/dde-clipboard/org.deepin.dde.Clipboard1.xml -a ./dde-clipboard/toolGenerate/qdbusxml2cpp/org.deepin.dde.Clipboard1Adaptor -i ./dde-clipboard/toolGenerate/qdbusxml2cpp/org.deepin.dde.Clipboard1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-clipboard/toolGenerate/qdbusxml2cpp/org.deepin.dde.Clipboard1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Clipboard1Adaptor
 */

Clipboard1Adaptor::Clipboard1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Clipboard1Adaptor::~Clipboard1Adaptor()
{
    // destructor
}

bool Clipboard1Adaptor::clipboardVisible() const
{
    // get the value of property clipboardVisible
    return qvariant_cast< bool >(parent()->property("clipboardVisible"));
}

void Clipboard1Adaptor::Hide()
{
    // handle method call org.deepin.dde.Clipboard1.Hide
    QMetaObject::invokeMethod(parent(), "Hide");
}

void Clipboard1Adaptor::Show()
{
    // handle method call org.deepin.dde.Clipboard1.Show
    QMetaObject::invokeMethod(parent(), "Show");
}

void Clipboard1Adaptor::Toggle()
{
    // handle method call org.deepin.dde.Clipboard1.Toggle
    QMetaObject::invokeMethod(parent(), "Toggle");
}

