/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-clipboard/dde-clipboard/org.deepin.dde.Clipboard1.xml -a ./dde-clipboard/toolGenerate/qdbusxml2cpp/org.deepin.dde.Clipboard1Adaptor -i ./dde-clipboard/toolGenerate/qdbusxml2cpp/org.deepin.dde.Clipboard1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_CLIPBOARD1ADAPTOR_H
#define ORG_DEEPIN_DDE_CLIPBOARD1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-clipboard/toolGenerate/qdbusxml2cpp/org.deepin.dde.Clipboard1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Clipboard1
 */
class Clipboard1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Clipboard1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Clipboard1\">\n"
"    <method name=\"Toggle\"/>\n"
"    <method name=\"Show\"/>\n"
"    <method name=\"Hide\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"clipboardVisible\"/>\n"
"    <signal name=\"clipboardVisibleChanged\">\n"
"      <arg type=\"b\" name=\"visible\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    Clipboard1Adaptor(QObject *parent);
    virtual ~Clipboard1Adaptor();

public: // PROPERTIES
    Q_PROPERTY(bool clipboardVisible READ clipboardVisible)
    bool clipboardVisible() const;

public Q_SLOTS: // METHODS
    void Hide();
    void Show();
    void Toggle();
Q_SIGNALS: // SIGNALS
    void clipboardVisibleChanged(bool visible);
};

#endif
