/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-clipboard/dde-clipboard-daemon/protocol/wlr-data-control-unstable-v1.xml -a ./dde-clipboard/toolGenerate/qdbusxml2cpp/wlr-data-control-unstable-v1Adaptor -i ./dde-clipboard/toolGenerate/qdbusxml2cpp/wlr-data-control-unstable-v1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-clipboard/toolGenerate/qdbusxml2cpp/wlr-data-control-unstable-v1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

